[package]
name = "loop_interchange_1"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench_loop_interchange_1"
harness = false

[dependencies]
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "real_blackbox", "cargo_bench_support"] }
